name: 'Hello Actions!'

on:
  pull_request:
    branch: master
  workflow_dispatch:

jobs:
  download-projeto:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: npm ci

      - name: Prettier
        run: npm run format
